# Generated by Django 5.2 on 2025-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificion', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('correo', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
