# Generated by Django 5.2 on 2025-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='identificion',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='identificacion',
            field=models.CharField(default='000000', max_length=45),
            preserve_default=False,
        ),
    ]
