# Generated by Django 5.2 on 2025-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='direccion',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='documento',
            field=models.CharField(default='0000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(default='1988-11-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(default='No especificado', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(default='Sin apellido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='usuario_generico', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
