# Generated by Django 5.2 on 2025-04-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vehiculos_taxistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxistas',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehiculos'),
        ),
    ]
