# Generated by Django 5.2 on 2025-05-12 01:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tarifa', models.IntegerField()),
                ('Taxistas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.taxistas')),
                ('Usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Vehiculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_usuario_a_taxista', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentarios_usaurio_a_taxista', models.TextField(blank=True, null=True)),
                ('calificacion_taxista_a_usuario', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentarios_taxistas_a_usuarios', models.TextField(blank=True, null=True)),
                ('fecha_usuario', models.DateTimeField(blank=True, null=True)),
                ('fecha_taxista', models.DateTimeField(blank=True, null=True)),
                ('Servicios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.servicios')),
            ],
        ),
    ]
