# Generated by Django 5.2 on 2025-04-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_taxistas_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=40)),
                ('destino', models.CharField(max_length=40)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxistas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.taxistas')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usuarios')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehiculos')),
            ],
        ),
    ]
