# Generated by Django 5.2 on 2025-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='taxistas',
            new_name='Taxistas',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='usuarios',
            new_name='Usuarios',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='vehiculo',
            new_name='Vehiculos',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='origen',
            field=models.CharField(max_length=100),
        ),
    ]
