# Generated by Django 5.2 on 2025-05-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='Taxistas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.taxistas'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='Usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicios',
            name='Vehiculos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehiculos'),
        ),
    ]
